[tool.poetry]
name = "tovana"
version = "0.0.8"
description = "Memory management system to enhance AI agents with personalized, context-aware responses"
authors = ["Assaf Elovic <assaf.elovic@gmail.com>", "Eden Marco <emarco177@gmail.com>"]
exclude = [
    "notebooks",
]
license = "Apache License 2.0"
readme = "README.md"
packages = [
    { include = "gptmem" },
]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.2.14"
langchain-openai = "^0.1.22"
aiofiles = "^24.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
isort = "^5.13.2"
pytest-xdist = "^3.6.1"
python-dotenv = "^1.0.1"
black = "^24.8.0"
langchain-anthropic = "^0.1.23"
langchain-mistralai = "^0.1.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
