[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "operator_precedence_high_roller"
version = "1.1.4"
authors = [
  { name="Jade Roberts", email="jaderobertsg2019@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/carsonrobertsg2019/operator-precedence-high-roller"

[tool.hatch.build.targets.sdist]
include = [
  "src",
  "tests",
  ".gitignore",
  "LICENSE",
  "pyproject.toml",
  "readme.md"
]
exclude = [
  "a.py",
  "__pycache__",
  "player_info.json",
  "get-pip.py",
  "bar_plot*"
]

[tool.hatch.build.targets.wheel]
packages = ["operator_precedence_high_roller"]