name: qusi_env
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2024.6.2=hf0a4a13_0
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.45.3=h091b4b1_0
  - libzlib=1.3.1=hfb2fe0b_1
  - ncurses=6.5=hb89a1cb_0
  - openssl=3.3.1=hfb2fe0b_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.11.9=h932a869_0_cpython
  - readline=8.2=h92ec313_1
  - setuptools=70.0.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h57fd34a_0
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - anyio==4.4.0
      - appnope==0.1.4
      - astropy==6.1.0
      - astropy-iers-data==0.2024.6.3.0.31.14
      - astroquery==0.4.7
      - asttokens==2.4.1
      - atpublic==4.1.0
      - attrs==23.2.0
      - autograd==1.6.2
      - babel==2.15.0
      - backcall==0.2.0
      - backports-strenum==1.2.8
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - bokeh==3.4.1
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distlib==0.3.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - docutils==0.21.2
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fbpca==1.0
      - filelock==3.14.0
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - furo==2024.5.6
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - hatch==1.12.0
      - hatchling==1.24.2
      - html5lib==1.1
      - httpcore==1.0.5
      - httpx==0.27.0
      - hyperlink==21.0.0
      - idna==3.7
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - iniconfig==2.0.0
      - ipython==8.12.3
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.1
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - keyring==25.2.1
      - kiwisolver==1.4.5
      - lightkurve==2.4.2
      - lightning==2.3.3
      - lightning-utilities==0.11.2
      - lxml==5.2.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.1
      - mdurl==0.1.2
      - memoization==0.4.0
      - mistune==3.0.2
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - myst-parser==3.0.1
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.3
      - numpy==1.26.4
      - oktopus==0.1.2
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - patsy==0.5.6
      - peewee==3.17.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.3.0
      - pipreqs==0.5.0
      - platformdirs==4.2.2
      - plotly==5.22.0
      - pluggy==1.5.0
      - polars==0.20.31
      - prompt-toolkit==3.0.46
      - protobuf==5.27.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.1.0
      - pyerfa==2.0.1.4
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pytest==7.4.4
      - pytest-asyncio==0.23.7
      - pytest-pycharm==0.7.0
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.3.3
      - pytz==2024.1
      - pyvo==1.5.2
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qusi==1.0.3
      - referencing==0.35.1
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.7.1
      - rpds-py==0.18.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sentry-sdk==2.5.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - sphinx==7.3.7
      - sphinx-basic-ng==1.0.0b2
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - stack-data==0.6.3
      - stringcase==1.2.0
      - sympy==1.12.1
      - tenacity==8.3.0
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tomli-w==1.0.0
      - tomlkit==0.12.5
      - torch==2.3.1
      - torcheval==0.0.7
      - torchmetrics==1.4.0.post0
      - torchvision==0.18.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - trove-classifiers==2024.5.22
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uncertainties==3.2.1
      - urllib3==2.2.1
      - userpath==1.9.2
      - uv==0.2.11
      - uvloop==0.19.0
      - virtualenv==20.26.2
      - wandb==0.17.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - xyzservices==2024.6.0
      - yarg==0.1.9
      - yarl==1.9.4
      - zipp==3.19.2
      - zstandard==0.22.0
prefix: /opt/homebrew/Caskroom/mambaforge/base/envs/qusi_env
