[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "dfndfl"
version = "1.1.1"
authors = [
    { name = "Andrea Petruzzi", email = "petruzzi.1982874@studenti.uniroma1.it" },
    { name = "Tommaso Giovannelli", email = "giovanto@ucmail.uc.edu" },
    { name = "Giampaolo Liuzzi", email = "liuzzi@diag.uniroma1.it" },
    { name = "Stefano Lucidi", email = "lucidi@diag.uniroma1.it" },
    { name = "Francesco Rinaldi", email = "rinaldi@math.unipd.it" },
]
description = "A package implementing DFNDFL, an algorithm that solves mixed-integer nonsmooth constrained optimization problems whose constraint functions are avaliable only as the oytput of a black-box zeroth-order oracle."
readme = "README.md"
dependencies = [
    "ghalton",
    "numpy",
    "sobol_seq",
]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent",
]

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/GreyJolly/DFNDFL-Package/"

[project.scripts]
run_problem = "run:main"

[tool]
