[tool.poetry]
name = "funcnodes-basic"
version = "0.1.4"
description = "Basic functionalities for funcnodes"
authors = ["Julian Kimmig <julian.kimmig@gmx.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
funcnodes = "*"
requests = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
