[tool.pdm]
package-dir = "src"

[tool.pdm.build]
locked = true
includes = [
    "src/openscm_zenodo",
    "LICENCE",
]

[tool.coverage.run]
source = [
    "src",
]
branch = true

[tool.coverage.report]
fail_under = 80
skip_empty = true
show_missing = true
exclude_also = [
    "if TYPE_CHECKING",
]

[tool.mypy]
strict = true
disallow_any_unimported = true
show_error_codes = true
show_error_context = true
warn_unreachable = true
follow_imports = "normal"

[tool.jupytext]
formats = "ipynb,py:percent"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ruff]
src = [
    "src",
]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "D",
    "PL",
    "TRY",
    "NPY",
    "RUF",
    "UP",
    "S",
]
unfixable = [
    "PD002",
]
ignore = [
    "D200",
    "D400",
    "UP007",
]

[tool.ruff.lint.per-file-ignores]
"test*.py" = [
    "D",
    "S101",
    "PLR2004",
]
"docs/*" = [
    "D100",
    "E402",
    "S101",
]
"scripts/*" = [
    "S101",
]
"stubs/*" = [
    "PLR0913",
]

[tool.ruff.lint.isort]
known-first-party = [
    "src",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
docstring-code-format = true

[tool.towncrier]
package = "openscm_zenodo"
package_dir = "src"
filename = "docs/changelog.md"
directory = "changelog/"
title_format = "## OpenSCM-Zenodo {version} ({project_date})"
underlines = [
    "",
    "",
    "",
]
issue_format = "[#{issue}](https://github.com/climate-resource/input4mips_validation/pulls/{issue})"
type = [
    { directory = "breaking", name = "âš ï¸ Breaking Changes", showcontent = true },
    { directory = "deprecation", name = "ðŸ—‘ï¸ Deprecations", showcontent = true },
    { directory = "feature", name = "ðŸ†• Features", showcontent = true },
    { directory = "improvement", name = "ðŸŽ‰ Improvements", showcontent = true },
    { directory = "fix", name = "ðŸ› Bug Fixes", showcontent = true },
    { directory = "docs", name = "ðŸ“š Improved Documentation", showcontent = true },
    { directory = "trivial", name = "ðŸ”§ Trivial/Internal Changes", showcontent = false },
]

[tool.liccheck]
authorized_licenses = [
    "bsd",
    "bsd license",
    "BSD 3-Clause",
    "CC0",
    "apache",
    "apache 2.0",
    "apache software",
    "apache software license",
    "Apache License, Version 2.0",
    "Historical Permission Notice and Disclaimer (HPND)",
    "isc license",
    "isc license (iscl)",
    "gnu lgpl",
    "lgpl with exceptions or zpl",
    "LGPLv2+",
    "GNU Lesser General Public License v2 (LGPLv2)",
    "GNU Lesser General Public License v2 or later (LGPLv2+)",
    "mit",
    "mit license",
    "Mozilla Public License 2.0 (MPL 2.0)",
    "python software foundation",
    "python software foundation license",
    "zpl 2.1",
]
unauthorized_licenses = [
    "agpl",
    "gnu agpl",
    "gpl v3",
    "gplv3",
    "gpl v2",
    "gplv2",
    "gpl v1",
    "gplv1",
]

[project]
name = "openscm-zenodo"
version = "0.2.6"
description = "Command-line tool for uploading to zenodo"
keywords = [
    "zenodo",
    "command-line",
]
readme = "README.md"
authors = [
    { name = "Zebedee Nicholls", email = "zebedee.nicholls@climate-energy-college.org" },
    { name = "Jared Lewis", email = "jared.lewis@climate-energy-college.org" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "requests",
    "tqdm",
    "typer",
    "loguru",
    "attrs",
]
requires-python = ">=3.9"

[project.license]
text = "3-Clause BSD License"

[project.urls]
Homepage = "https://github.com/openscm/openscm-zenodo"
"Bug Reports" = "https://github.com/openscm/openscm-zenodo/issues"
Documentation = "https://openscm-zenodo.readthedocs.io/"
Source = "https://github.com/openscm/openscm-zenodo"

[project.optional-dependencies]
dev = [
    "mypy>=1.11.1",
    "pre-commit>=3.8.0",
    "types-tqdm>=4.66.0.20240417",
    "types-requests>=2.32.0.20240712",
    "towncrier>=23.11.0,<24",
    "liccheck>=0.9.2",
    "pip>=24.2",
    "websocket-client>=1.8.0",
]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.32",
    "mkdocstrings[python]>=0.25.2",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-section-index>=0.3.9",
    "mkdocs-autorefs>=1.0.1",
    "mkdocs-jupyter>=0.24.8",
    "jupyterlab>=4.2.4",
    "jupytext>=1.16.4",
]
notebooks = [
    "jupyterlab>=4.2.4",
]
tests = [
    "pytest>=8.3.2",
    "coverage>=7.6.1",
    "pytest-cov>=5.0.0",
]
locked = [
    "attrs==24.2.0",
    "certifi==2024.7.4",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "colorama==0.4.6",
    "idna==3.7",
    "loguru==0.7.2",
    "markdown-it-py==3.0.0",
    "mdurl==0.1.2",
    "pygments==2.18.0",
    "requests==2.32.3",
    "rich==13.7.1",
    "shellingham==1.5.4",
    "tqdm==4.66.5",
    "typer==0.12.4",
    "typing-extensions==4.12.2",
    "urllib3==2.2.2",
    "win32-setctime==1.1.0 ; sys_platform == \"win32\"",
]
dev-locked = [
    "cfgv==3.4.0",
    "click==8.1.7",
    "colorama==0.4.6",
    "distlib==0.3.8",
    "filelock==3.15.4",
    "identify==2.6.0",
    "importlib-resources==6.4.3 ; python_version < \"3.10\"",
    "incremental==24.7.2",
    "jinja2==3.1.4",
    "liccheck==0.9.2",
    "markupsafe==2.1.5",
    "mypy==1.11.1",
    "mypy-extensions==1.0.0",
    "nodeenv==1.9.1",
    "pip==24.2",
    "platformdirs==4.2.2",
    "pre-commit==3.8.0",
    "pyyaml==6.0.2",
    "semantic-version==2.10.0",
    "setuptools==73.0.1",
    "toml==0.10.2",
    "tomli==2.0.1 ; python_version < \"3.11\"",
    "towncrier==23.11.0",
    "types-requests==2.32.0.20240712",
    "types-tqdm==4.66.0.20240417",
    "typing-extensions==4.12.2",
    "urllib3==2.2.2",
    "virtualenv==20.26.3",
    "websocket-client==1.8.0",
    "zipp==3.20.0 ; python_version < \"3.10\"",
]
docs-locked = [
    "anyio==4.4.0",
    "appnope==0.1.4 ; platform_system == \"Darwin\"",
    "argon2-cffi==23.1.0",
    "argon2-cffi-bindings==21.2.0",
    "arrow==1.3.0",
    "asttokens==2.4.1",
    "async-lru==2.0.4",
    "attrs==24.2.0",
    "babel==2.16.0",
    "beautifulsoup4==4.12.3",
    "bleach==6.1.0",
    "certifi==2024.7.4",
    "cffi==1.17.0",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "colorama==0.4.6",
    "comm==0.2.2",
    "debugpy==1.8.5",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "exceptiongroup==1.2.2 ; python_version < \"3.11\"",
    "executing==2.0.1",
    "fastjsonschema==2.20.0",
    "fqdn==1.5.1",
    "ghp-import==2.1.0",
    "griffe==1.1.1",
    "h11==0.14.0",
    "httpcore==1.0.5",
    "httpx==0.27.0",
    "idna==3.7",
    "importlib-metadata==8.4.0 ; python_version < \"3.10\"",
    "ipykernel==6.29.5",
    "ipython==8.18.1",
    "isoduration==20.11.0",
    "jedi==0.19.1",
    "jinja2==3.1.4",
    "json5==0.9.25",
    "jsonpointer==3.0.0",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2023.12.1",
    "jsonschema[format-nongpl]==4.23.0",
    "jupyter-client==8.6.2",
    "jupyter-core==5.7.2",
    "jupyter-events==0.10.0",
    "jupyter-lsp==2.2.5",
    "jupyter-server==2.14.2",
    "jupyter-server-terminals==0.5.3",
    "jupyterlab==4.2.4",
    "jupyterlab-pygments==0.3.0",
    "jupyterlab-server==2.27.3",
    "jupytext==1.16.4",
    "markdown==3.7",
    "markdown-it-py==3.0.0",
    "markupsafe==2.1.5",
    "matplotlib-inline==0.1.7",
    "mdit-py-plugins==0.4.1",
    "mdurl==0.1.2",
    "mergedeep==1.3.4",
    "mistune==3.0.2",
    "mkdocs==1.6.0",
    "mkdocs-autorefs==1.1.0",
    "mkdocs-gen-files==0.5.0",
    "mkdocs-get-deps==0.2.0",
    "mkdocs-jupyter==0.24.8",
    "mkdocs-literate-nav==0.6.1",
    "mkdocs-material==9.5.32",
    "mkdocs-material-extensions==1.3.1",
    "mkdocs-section-index==0.3.9",
    "mkdocstrings==0.25.2",
    "mkdocstrings-python==1.10.8",
    "mkdocstrings[python]==0.25.2",
    "nbclient==0.10.0",
    "nbconvert==7.16.4",
    "nbformat==5.10.4",
    "nest-asyncio==1.6.0",
    "notebook-shim==0.2.4",
    "overrides==7.7.0",
    "packaging==24.1",
    "paginate==0.5.6",
    "pandocfilters==1.5.1",
    "parso==0.8.4",
    "pathspec==0.12.1",
    "pexpect==4.9.0 ; sys_platform != \"win32\"",
    "platformdirs==4.2.2",
    "prometheus-client==0.20.0",
    "prompt-toolkit==3.0.47",
    "psutil==6.0.0",
    "ptyprocess==0.7.0 ; os_name != \"nt\" or sys_platform != \"win32\"",
    "pure-eval==0.2.3",
    "pycparser==2.22",
    "pygments==2.18.0",
    "pymdown-extensions==10.9",
    "python-dateutil==2.9.0.post0",
    "python-json-logger==2.0.7",
    "pywin32==306 ; sys_platform == \"win32\" and platform_python_implementation != \"PyPy\"",
    "pywinpty==2.0.13 ; os_name == \"nt\"",
    "pyyaml==6.0.2",
    "pyyaml-env-tag==0.1",
    "pyzmq==26.1.1",
    "referencing==0.35.1",
    "regex==2024.7.24",
    "requests==2.32.3",
    "rfc3339-validator==0.1.4",
    "rfc3986-validator==0.1.1",
    "rpds-py==0.20.0",
    "send2trash==1.8.3",
    "setuptools==73.0.1",
    "six==1.16.0",
    "sniffio==1.3.1",
    "soupsieve==2.6",
    "stack-data==0.6.3",
    "terminado==0.18.1",
    "tinycss2==1.3.0",
    "tomli==2.0.1 ; python_version < \"3.11\"",
    "tornado==6.4.1",
    "traitlets==5.14.3",
    "types-python-dateutil==2.9.0.20240821",
    "typing-extensions==4.12.2",
    "uri-template==1.3.0",
    "urllib3==2.2.2",
    "watchdog==4.0.2",
    "wcwidth==0.2.13",
    "webcolors==24.8.0",
    "webencodings==0.5.1",
    "websocket-client==1.8.0",
    "zipp==3.20.0 ; python_version < \"3.10\"",
]
notebooks-locked = [
    "anyio==4.4.0",
    "appnope==0.1.4 ; platform_system == \"Darwin\"",
    "argon2-cffi==23.1.0",
    "argon2-cffi-bindings==21.2.0",
    "arrow==1.3.0",
    "asttokens==2.4.1",
    "async-lru==2.0.4",
    "attrs==24.2.0",
    "babel==2.16.0",
    "beautifulsoup4==4.12.3",
    "bleach==6.1.0",
    "certifi==2024.7.4",
    "cffi==1.17.0",
    "charset-normalizer==3.3.2",
    "colorama==0.4.6",
    "comm==0.2.2",
    "debugpy==1.8.5",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "exceptiongroup==1.2.2 ; python_version < \"3.11\"",
    "executing==2.0.1",
    "fastjsonschema==2.20.0",
    "fqdn==1.5.1",
    "h11==0.14.0",
    "httpcore==1.0.5",
    "httpx==0.27.0",
    "idna==3.7",
    "importlib-metadata==8.4.0 ; python_version < \"3.10\"",
    "ipykernel==6.29.5",
    "ipython==8.18.1",
    "isoduration==20.11.0",
    "jedi==0.19.1",
    "jinja2==3.1.4",
    "json5==0.9.25",
    "jsonpointer==3.0.0",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2023.12.1",
    "jsonschema[format-nongpl]==4.23.0",
    "jupyter-client==8.6.2",
    "jupyter-core==5.7.2",
    "jupyter-events==0.10.0",
    "jupyter-lsp==2.2.5",
    "jupyter-server==2.14.2",
    "jupyter-server-terminals==0.5.3",
    "jupyterlab==4.2.4",
    "jupyterlab-pygments==0.3.0",
    "jupyterlab-server==2.27.3",
    "markupsafe==2.1.5",
    "matplotlib-inline==0.1.7",
    "mistune==3.0.2",
    "nbclient==0.10.0",
    "nbconvert==7.16.4",
    "nbformat==5.10.4",
    "nest-asyncio==1.6.0",
    "notebook-shim==0.2.4",
    "overrides==7.7.0",
    "packaging==24.1",
    "pandocfilters==1.5.1",
    "parso==0.8.4",
    "pexpect==4.9.0 ; sys_platform != \"win32\"",
    "platformdirs==4.2.2",
    "prometheus-client==0.20.0",
    "prompt-toolkit==3.0.47",
    "psutil==6.0.0",
    "ptyprocess==0.7.0 ; os_name != \"nt\" or sys_platform != \"win32\"",
    "pure-eval==0.2.3",
    "pycparser==2.22",
    "pygments==2.18.0",
    "python-dateutil==2.9.0.post0",
    "python-json-logger==2.0.7",
    "pywin32==306 ; sys_platform == \"win32\" and platform_python_implementation != \"PyPy\"",
    "pywinpty==2.0.13 ; os_name == \"nt\"",
    "pyyaml==6.0.2",
    "pyzmq==26.1.1",
    "referencing==0.35.1",
    "requests==2.32.3",
    "rfc3339-validator==0.1.4",
    "rfc3986-validator==0.1.1",
    "rpds-py==0.20.0",
    "send2trash==1.8.3",
    "setuptools==73.0.1",
    "six==1.16.0",
    "sniffio==1.3.1",
    "soupsieve==2.6",
    "stack-data==0.6.3",
    "terminado==0.18.1",
    "tinycss2==1.3.0",
    "tomli==2.0.1 ; python_version < \"3.11\"",
    "tornado==6.4.1",
    "traitlets==5.14.3",
    "types-python-dateutil==2.9.0.20240821",
    "typing-extensions==4.12.2",
    "uri-template==1.3.0",
    "urllib3==2.2.2",
    "wcwidth==0.2.13",
    "webcolors==24.8.0",
    "webencodings==0.5.1",
    "websocket-client==1.8.0",
    "zipp==3.20.0 ; python_version < \"3.10\"",
]
tests-locked = [
    "colorama==0.4.6",
    "coverage==7.6.1",
    "coverage[toml]==7.6.1",
    "exceptiongroup==1.2.2 ; python_version < \"3.11\"",
    "iniconfig==2.0.0",
    "packaging==24.1",
    "pluggy==1.5.0",
    "pytest==8.3.2",
    "pytest-cov==5.0.0",
    "tomli==2.0.1 ; python_version < \"3.11\"",
]

[project.scripts]
openscm-zenodo = "openscm_zenodo.cli:app"

[build-system]
requires = [
    "pdm-backend",
    "pdm-build-locked",
]
build-backend = "pdm.backend"
