[tool.poetry]
name = "allskycam4oleodl"
version = "0.3.1"
description = "Tracking software for OLEODL using Allied Vision cameras. Developed alongside DLR-OP-IKN."
authors = ["Iker Aldasoro <ikeraldasorot@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Ikerald/AllSkyCam4OLEODL"
repository = "https://github.com/Ikerald/AllSkyCam4OLEODL"
keywords = ["OLEODL", "AllSky"]
packages = [{include = "AllSkyCam4OLEODL"}]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.21.6"
opencv-python = "^4.5.5.64"
matplotlib = "^3.5.3"
mplcursors = "^0.5.1"
scipy = "^1.7.3"
tk = "*"
pytz = "^2021.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
