[project]
name = "zuu"
version = "0.1.10"
description = "zackary's useful utilities"
authors = [
    { name = "ZackaryW", email = "gitzackw@gmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[project.scripts]
zuu = "zuu.tool.__main__:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.2",
    "keyring>=25.3.0",
    "cryptography>=43.0.0",
    "psutil>=6.0.0",
    "pyautogui>=0.9.54",
    "screeninfo>=0.8.1",
    "pygetwindow>=0.0.9",
    "numpy>=2.0.1",
    "click>=8.1.7",
    "discord>=2.3.2",
    "pyyaml>=6.0.2",
    "toml>=0.10.2",
    "requests>=2.32.3",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/zuu"]

[tool.ruff]
ignore = ["F401"]
