[tool.poetry]
name = "bizon"
version = "0.0.2"
description = "Extract and load your data reliably from API Clients with native fault-tolerant and checkpointing mechanism."
authors = ["Antoine Balliet <antoine.balliet@gmail.com>", "Anas El Mhamdi <anas.elmhamdi@gmail.com>"]
readme = "README.md"
packages = [{include = "bizon"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
requests = "^2.28.2"
pyyaml = "^6.0.1"
pydantic = "^2.8.2"
backoff = "^2.2.1"
pendulum = "^3.0.0"
dpath = "^2.2.0"
pydantic-extra-types = "^2.9.0"
loguru = "^0.7.2"
pandas = "^2.2.2"
pyarrow = "^16.1.0"
google-cloud-storage = "^2.17.0"
faker = "^26.0.0"
sqlalchemy = "^2.0.32"


###### Backend / Destinations ######
# Postgres
[tool.poetry.group.postgres.dependencies]
psycopg2-binary = "^2.9.9"

# BigQuery
[tool.poetry.group.bigquery.dependencies]
google-cloud-bigquery-storage = "^2.25.0"
google-cloud-bigquery = "^3.25.0"
sqlalchemy-bigquery = "^1.11.0"

###### Queues ######
[tool.poetry.group.kafka.dependencies]
kafka-python = "^2.0.2"

[tool.poetry.group.rabbitmq.dependencies]
pika = "^1.3.2"

###### [Test] dependencies ######
[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"
requests-mock = "^1.10.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
snakeviz = "^2.1.2"
yappi = "^1.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"