[tool.poetry]
name = "battery_management"
version = "v0.1.4"
description = "Battery Optimization"
authors = ["Abdelrashied, Mostafa <Mostafa.Abdelrashied@outlook.de>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "battery_management" }]


[tool.poetry.dependencies]
python = ">=3.8,<3.12"
loguru = "^0.7.2"
ortools = "^9.10.4067"
numpy = "^1.24.4"
pandas = "^2.0.2"
matplotlib = "^3.7.5"
mip = "^1.15.0"
scipy = "^1.10.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.0"
pre-commit = "^3.5.0"
coverage = "^7.6.0"
ipykernel = "^6.29.5"
mock = "^5.1.0"
pytest = "^8.3.2"
bumpver = "^2023.1129"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.bumpver]
current_version = "v0.1.4"
version_pattern = "vMAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['^version = "{version}"', '^current_version = "{version}"']
"battery_management/__init__.py" = ['^__version__ = "{version}"']
