[project]
name = "mentalweather"
version = "0.0.1"
authors = [
  { name="Shih-Yen Hung", email="syhung@gapp.nthu.edu.tw" },
]
description = "A package including the analysis of relationship between mental disease and weather and an application based on the ML model"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/ShihYenHung/SCE_SY"
Issues = "https://github.com/ShihYenHung/SCE_SY/issues"