[tool.poetry]
name = "readme-builder"
version = "0.1.2"
description = "Create contextual README.md files"
authors = ["Akshita Dixit <akshitadixit.int@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
requests = "2.32.3"

[tool.poetry.scripts]
build-readme = "readme_builder.cli:main"

[tool.poetry.dev-dependencies]
ruff = "^0.6.2"

[tool.ruff]
line-length = 90
exclude = ["*.pyi"]

[tool.ruff.lint]
select = [
  "PL", # Pylint
  "F", # Pyflakes
  "I", # isort
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
]

[tool.ruff.lint.pylint]
max-statements = 50

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
