[build-system]
requires = [
    "wheel>0.33",
    "meson[ninja]>1.1.0",
    'tomli>=2.0.0;python_version<"3.11"',
    "setuptools>=64",
]
backend-path = [".", "ozi_build"]
build-backend = "ozi_build.buildapi"

[project.optional_dependencies]
# ozi-spec version 0.8
# core build dependencies
core = [
    "invoke~=2.2",
    "pip-tools>=7",
    "pipx~=1.5",
    "setuptools_scm[toml]~=8.0",
]
uv = ["uv"]
cython = ["cython~=3.0"]

[tool.ozi-build.metadata]
meson-python-option-name="python_version"
author="Thibault Saunier"
author-email="tsaunier@gnome.org"
maintainer="Eden Ross Duff MSc"
maintainer-email="help@oziproject.dev"
summary="Create pep517 compliant packages from the meson build system, OZI-maintained fork."
home-page="https://oziproject.dev"
description-file="README.rst"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Build Tools",
    "Topic :: System :: Archiving :: Packaging",
    "Development Status :: 4 - Beta",
]
requires-python="py3-none"
requires = [
    "wheel>0.33",
    "meson[ninja]>1.1.0",
    'tomli>=2.0.0;python_version<"3.11"',
    "setuptools",
]
project-urls= [
    "Source, https://github.com/OZI-Project/OZI.build",
    "Documentation, https://docs.oziproject.dev/en/stable/ozi_build.html",
]