[build-system]
   requires = ["setuptools>=61.0", "wheel"]
   build-backend = "setuptools.build_meta"

[project]
   name = "biblatex2qmd"
   version = "0.1.2"
   description = "BibLaTeX Processor is a Python package that processes BibLaTeX files, extracts information from each entry, creates individual Markdown files for each entry, and generates a combined corpus file."
   readme = "README.md"
   authors = [{ name = "Jan-Ru Muller", email = "janru.muller@edu.vlerick.com" }]
   license = { file = "LICENSE" }
   classifiers = [
       "License :: OSI Approved :: MIT License",
       "Programming Language :: Python",
       "Programming Language :: Python :: 3",
   ]
   keywords = ["bib", "latex", "processor"]
   dependencies = [
       "bibtexparser",
       "pytest"
   ]
   requires-python = ">=3.7"

   [tool.setuptools.packages.find]
   where = ["src"]
   include = ["biblatex2qmd*"]

[project.urls]
   Homepage = "https://github.com/jan-ru/biblatex2qmd"

[project.scripts]
   biblatex2qmd = "biblatex2qmd.bib_processor:main"
   
