[tool.poetry]
name = "fotetizar"
version = "0.1.51"
description = "A tool to generate images from code with different themes."
authors = ["Torrez, Milton <torrez.mn@gmail.com>"]
readme = ["docs/README.md"]
license = "MIT"
keywords = ["code", "share_code", "images"]
packages = [
{ include = "fotetizar" },  # For code in a custom directory named "mypackage"
]

[tool.poetry.dependencies]
python = "^3.8"
pillow = "^10.4.0"




[tool.poetry.scripts]
code2image = "code2image.fotetizar:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

