[tool.poetry]
name = "vbtikztoanimation"
version = "0.1.1"
description = ""
authors = ["vaibhavblayer <vaibhavblayer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"


[tool.poetry.scripts]
vbtikztoanimation = "vbtikztoanimation.__main__:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
