[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "griffe-endstone"
version = "0.1.1"
dependencies = ["griffe"]
authors = [
    { name = "Vincent", email = "magicdroidx@gmail.com" },
]
description = "Griffe extension for the Endstone project."
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["endstone", "griffe-extension", "mkdocstrings"]
